version: "3.8"

services:

  web-service:
    container_name: web-service
    build: ./services/web/sgq-app/
    volumes:
      - ./services/web/sgq-app/:/usr/src/app
      - web-node-modules:/usr/src/app/node_modules
    ports:
      - '9000:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - api-gateway
    networks:
      - microservices

  api-gateway:
    container_name: api-gateway
    build: ./services/api-gateway/
    restart: unless-stopped
    ports:
      - 3000:3000 # host:container
    networks:
      - microservices

  bi-module:
    container_name: bi-module
    build: ./services/bi-module/
    restart: unless-stopped
    ports:
      - 3001:3001 # host:container
    networks:
      - microservices

  compliance-module:
    container_name: compliance-module
    build: ./services/compliance-module/
    restart: unless-stopped
    ports:
      - 3002:3002 # host:container
    networks:
      - microservices

  divulgation-module:
    container_name: divulgation-module
    build: ./services/divulgation-module/
    restart: unless-stopped
    ports:
      - 3003:3003 # host:container
    networks:
      - microservices

  incidents-module:
    container_name: incidents-module
    build: ./services/incidents-module/
    restart: unless-stopped
    ports:
      - 3004:3004 # host:container
    networks:
      - microservices

  non-conformities-module:
    container_name: non-conformities-module
    build: ./services/non-conformities-module/
    restart: unless-stopped
    ports:
      - 3005:3005 # host:container
    networks:
      - microservices

  processes-module:
    container_name: processes-module
    build: ./services/processes-module/
    restart: unless-stopped
    ports:
      - 3006:3006 # host:container
    networks:
      - microservices

  incidents-db:
    container_name: incidents-db
    image: mysql:5.7 # mysql 8 is not supported by mysql.js
    restart: always
    command: --init-file /data/application/init_db.sql
    environment:
      MYSQL_DATABASE: 'incidents_db'
      MYSQL_USER: 'sgq'
      MYSQL_PASSWORD: 'sgq'
      MYSQL_ROOT_PASSWORD: 'not_123456'
    volumes:
      - incidents-db:/var/lib/mysql
      - ./services/incidents-module/db/init_db.sql:/data/application/init_db.sql
    networks:
      - microservices

  non-conformities-db:
    container_name: non-conformities-db
    image: mysql:5.7 # mysql 8 is not supported by mysql.js
    restart: always
    command: --init-file /data/application/init_db.sql
    environment:
      MYSQL_DATABASE: 'non_conformities_db'
      MYSQL_USER: 'sgq'
      MYSQL_PASSWORD: 'sgq'
      MYSQL_ROOT_PASSWORD: 'not_123456'
    volumes:
      - non-conformities-db:/var/lib/mysql
      - ./services/non-conformities-module/db/init_db.sql:/data/application/init_db.sql
    networks:
      - microservices

  processes-db:
    container_name: processes-db
    image: mysql:5.7 # mysql 8 is not supported by mysql.js
    restart: always
    command: --init-file /data/application/init_db.sql
    environment:
      MYSQL_DATABASE: 'non_conformities_db'
      MYSQL_USER: 'sgq'
      MYSQL_PASSWORD: 'sgq'
      MYSQL_ROOT_PASSWORD: 'not_123456'
    volumes:
      - processes-db:/var/lib/mysql
      - ./services/processes-module/db/init_db.sql:/data/application/init_db.sql
    networks:
      - microservices

networks:
    microservices:

volumes:
  incidents-db:
  non-conformities-db:
  processes-db:
  web-node-modules: