version: "3"

services:

  processes-module:
    image: mathiasfk/sgq-processes-module:1.0.0
    build: ../services/processes-module/
    ports:
      - 3006:3006 # host:container
    networks:
      - microservices

  processes-db:
    image: mathiasfk/sgq-processes-db:1.0.0
    build: ../services/processes-module/db/
    command: --init-file /data/application/init_db.sql
    environment:
      MYSQL_DATABASE: 'processes-db'
      MYSQL_ROOT_PASSWORD: 'not_123456'
    volumes:
      - processes-db:/var/lib/mysql
    networks:
      - microservices
    logging:
      driver: awslogs
      options: 
        awslogs-group: sgq
        awslogs-region: us-west-2
        awslogs-stream-prefix: processes-db

networks:
    microservices:

volumes:
  incidents-db:
  non-conformities-db:
  processes-db:
  web-node-modules: