version: "3"

services:

  web-service:
    image: mathiasfk/sgq-web-service:1.0.0
    build: 
      context: ../services/web/sgq-app/
      dockerfile: Dockerfile-prod
    volumes:
      - web-node-modules:/usr/src/app/node_modules
    ports:
      - '80:80' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - REACT_APP_API_URL=http://35.165.192.220
    networks:
      - microservices
    logging:
      driver: awslogs
      options: 
        awslogs-group: sgq
        awslogs-region: us-west-2
        awslogs-stream-prefix: web

networks:
    microservices:

volumes:
  incidents-db:
  non-conformities-db:
  processes-db:
  web-node-modules: