version: "3"

services:

  auth-service:
    image: mathiasfk/sgq-auth-service:1.0.0
    build: ../services/auth-service/
    ports:
      - 4000:4000
    networks:
      - microservices
    logging:
      driver: awslogs
      options: 
        awslogs-group: sgq
        awslogs-region: us-west-2
        awslogs-stream-prefix: auth

  mongo:
    image: mongo:3.6.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongorootpassword
    networks:
      - microservices
    logging:
      driver: awslogs
      options: 
        awslogs-group: sgq
        awslogs-region: us-west-2
        awslogs-stream-prefix: mongo

networks:
    microservices:

volumes:
  incidents-db:
  non-conformities-db:
  processes-db:
  web-node-modules: